### ISSUE TITLE
Same prop names overriding

### ISSUE THREAD

**Issue by Ilanaya** [maIIady/vscode-tailwind-in-css#13]
If the rule props are the same the last will override previous, what will cause the previous one not to be counted as already used.
This is because of setting is the `usedRules` Map() based on rule prop, looks like it's gonna be better to use shortcut's name instead

![image](https://user-images.githubusercontent.com/74474615/178125131-8a72f681-2829-416f-b6e2-b4ddeb7d5552.png)

**Comment by zardoy** [comment]
I literally didn't get you. Try to rebuild the last sentence, some code samples / links are also welcome

**Comment by Ilanaya** [comment]
Sorry, this issue is related to [this pr](https://github.com/ILScc/vscode-tailwind-in-css/pull/12), gonna give better explanation in comments
