### ISSUE TITLE
Initializing bug

### ISSUE THREAD

**Issue by Ilanaya** [maIIady/vscode-tailwind-in-css#20]
![image](https://user-images.githubusercontent.com/74474615/199074666-80914669-ae2f-4d40-bab9-f9910fdd837e.png)

**Comment by zardoy** [comment]
Just rename it to `usedShortcuts.enabled`. Fixed it in the past: https://github.com/zardoy/typescript-vscode-plugins/commit/7f63001cbdad2a0dae22c850dfc7758ca44bd336
