### ISSUE TITLE
Add JavaScript as a active language

### ISSUE THREAD

**Issue by alvarosoaress** [maIIady/vscode-tailwind-in-css#25]
Hello ! 
I was looking for a extension to write tailwind syntax inside a styled component, only to make the css write part more simpler. 
Your extension does that but, not inside a JS file.
Can you add JavaScript file support to your extension please? 
Thanks !

**Comment by zardoy** [comment]
@alvarosoaress Hey! Just to clarify, things, we're gonna push support for tag literal (as I can understand from your body), e.g.:

```ts
const Custom = styled.div`
    |
`
```

But note that there is also object syntax which is also valid on some cases of such css-in-js lib:

```tsx
;<Globals css={{
    // |flex ->
    display: "flex"
}} />
```

We're not gonna add this support until there is such request.

For example [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components) works in similar way: adding emmet completions only inside `styled` tag (e.g. try this code: `` styled.div`p3` ``).
